theme: minima
title: Not a Blog
author: ZehraSikira
email: zehrasikira1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is everything but a blog!

# social links
twitter_username: twitterusername # DO NOT include the @ character, or else the build will fail!
github_username:  ZehraSikira # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
